seed: 42
project_dir_path: /n/davies_lab/Users/luciagordon/mmearth-bench
epochs: 200
nodata_value: -9999

hydra:
  job:
    chdir: true
  run:
    dir: ${project_dir_path}/experiments/${task}/${model_type}/${env:JOB_ID}

logger:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  entity: luciagordon-harvard-university
  project: mmearth-bench
  name: ${task}_${model_type}_${adaptation_mode}_${env:JOB_ID}
  log_model: true

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${epochs}
  logger: ${logger}
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  deterministic: true
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: "Val loss"
      save_last: true
      dirpath: checkpoints
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step

datamodule:
  _target_: datamodule.DataModule
  task: ${task}
  batch_size: 64
  data_dir_path: ${project_dir_path}
  num_workers: 1
  seed: ${seed}

model:
  _target_: model.Model
  task: ${task}
  model: ${model_type}
  adaptation_mode: ${adaptation_mode}
  decay_factor: 0.9
  max_lr: 0.0001
  weight_decay: 0.01
  warmup_epochs: 20
  num_train_batches: null
  min_lr: 1e-6
  epochs: ${epochs}
  nodata_value: ${nodata_value}
