seed: 41
epochs: 100
data_dir_path: '/n/gajos_lab/Lab/luciagordon/mmearth-bench'

hydra:
  job:
    chdir: true
  run:
    dir: /tmp/${task}_${architecture}_${adaptation_mode}_${train_percent}_${env:JOB_ID}

logger:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  entity: luciagordon-harvard-university
  project: mmearth-bench
  name: ${task}_${architecture}_${adaptation_mode}_${train_percent}_${env:JOB_ID}
  log_model: true
  tags: ["pi_41"]

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${epochs}
  logger: ${logger}
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  deterministic: true
  inference_mode: false
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: "Val R2"
      mode: max
      save_last: true
      dirpath: checkpoints
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step

datamodule:
  _target_: datamodule.DataModule
  task: ${task}
  architecture: ${architecture}
  adaptation_mode: ${adaptation_mode}
  train_percent: ${train_percent}
  batch_size: 64
  num_workers: 1
  seed: ${seed}

model:
  _target_: model.Model
  task: ${task}
  architecture: ${architecture}
  adaptation_mode: ${adaptation_mode}
  pretrained: true
  max_lr: 1e-4
  weight_decay: 0.05
  warmup_epochs: 10
  num_train_batches: null
  min_lr: 1e-6
  epochs: ${epochs}
  inner_loop_lr: 1e-2
  seed: ${seed}
