seed: 42
epochs: 200
data_dir_path: '/n/gajos_lab/Lab/luciagordon/mmearth-bench-new'

hydra:
  job:
    chdir: true
  run:
    dir: /tmp/${task}_${architecture}_${env:JOB_ID}

logger:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  entity: luciagordon-harvard-university
  project: mmearth-bench
  name: ${task}_${architecture}_${adaptation_mode}_${env:JOB_ID}
  log_model: true

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${epochs}
  logger: ${logger}
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  deterministic: true
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: "Val loss"
      save_last: true
      dirpath: checkpoints
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step

datamodule:
  _target_: datamodule.DataModule
  task: ${task}
  batch_size: 32
  num_workers: 1
  seed: ${seed}

model:
  _target_: model.Model
  task: ${task}
  architecture: ${architecture}
  adaptation_mode: ${adaptation_mode}
  tuning_mode: ft
  pretrained: true
  decay_factor: 0.9
  max_lr: 0.001
  weight_decay: 0.01
  warmup_epochs: 20
  num_train_batches: null
  min_lr: 1e-6
  epochs: ${epochs}
